name: Build dorsetc

on:
  push

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Configure Build
        run: cmake -B build -DCMAKE_C_COMPILER="/usr/bin/clang-18" -DCMAKE_CXX_COMPILER="/usr/bin/clang++-18" -DLLVM_DIR="/usr/lib/llvm-18/cmake" dorsetc

      - name: Build dorsetc
        run: cmake --build build --config Release

      - name: Test
        working-directory: build/test
        run: ctest --build-config Release --verbose

      - name: Emit Version
        run: build/bin/dorsetc/dorsetc --version

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dorset-lang-build
      #     path: |
      #       build/dorsetc
      #       build/libdorsetDriver.a
